package org.dhole.internal.web;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.nio.charset.StandardCharsets;
import java.util.Optional;

import example.hello.App;
import example.hello.controllers.HelloController;
import org.junit.jupiter.api.Test;

/**
 * Black-box test of hello-api over real HTTP. The component index was generated by the metadata
 * compiler while Gradle compiled hello-api; the internal WebRuntime (M5 test launcher) builds the
 * container, finds the controller root, registers its routes and serves them on an ephemeral port.
 * The application's own entry point stays Dhole.run(App.class).
 *
 * <p>Lives in the web runtime's package to reach its internal API.
 */
class HelloApiTest {

    @Test
    void getHelloServesHelloWorld() throws Exception {
        try (WebRuntime runtime = WebRuntime.start(App.class.getClassLoader(), "127.0.0.1", 0);
                HttpClient client = HttpClient.newHttpClient()) {
            HttpResponse<String> response = client.send(
                    HttpRequest.newBuilder(URI.create("http://127.0.0.1:" + runtime.port() + "/hello")).build(),
                    BodyHandlers.ofString());

            assertEquals(200, response.statusCode());
            assertEquals("Hello World", response.body());
            assertEquals(Optional.of("text/plain; charset=UTF-8"), response.headers().firstValue("Content-Type"));
        }
    }

    @Test
    void helloControllerIsAStructuralRootInTheGeneratedIndex() throws IOException {
        String index;
        try (InputStream input = App.class.getClassLoader().getResourceAsStream("META-INF/dhole/components.idx")) {
            index = new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }

        assertTrue(index.startsWith("dhole-metadata 1\n"), index);
        assertTrue(index.contains("component " + HelloController.class.getName() + "\nconstructor\n"
                + "supertype org.dhole.web.Controller\n"), index);
    }
}
