package org.dhole.internal.web;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.nio.charset.StandardCharsets;
import java.util.Optional;

import example.hello.App;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Typed routes of hello-api over real HTTP: routes.idx was generated by the metadata compiler while
 * Gradle compiled hello-api; the internal WebRuntime binds and serves them on an ephemeral port.
 */
class UsersApiTest {

    private final HttpClient client = HttpClient.newHttpClient();
    private WebRuntime runtime;

    @BeforeEach
    void start() {
        runtime = WebRuntime.start(App.class.getClassLoader(), "127.0.0.1", 0);
    }

    @AfterEach
    void stop() {
        runtime.close();
        client.close();
    }

    @Test
    void generatedRouteIndexDescribesTheTypedRoutes() throws IOException {
        String index;
        try (InputStream input = App.class.getClassLoader().getResourceAsStream("META-INF/dhole/routes.idx")) {
            index = new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }

        assertTrue(index.contains("route example.hello.users.UserController GET /users/{id}\nhandler find\n"
                + "parameter id PATH long\nresponse example.hello.users.User\n"), index);
        assertTrue(index.contains("route example.hello.users.UserController POST /users\nhandler create\n"
                + "parameter input BODY example.hello.users.CreateUser\n"), index);
    }

    @Test
    void getUserBindsThePathAndReturnsJson() throws Exception {
        HttpResponse<String> response = send("GET", "/users/42", null, null, "application/json");

        assertEquals(200, response.statusCode());
        assertEquals("{\"id\":42,\"name\":\"User 42\",\"email\":\"user42@example.com\"}", response.body());
        assertEquals(Optional.of("application/json"), response.headers().firstValue("Content-Type"));
    }

    @Test
    void postUserBindsTheJsonBody() throws Exception {
        HttpResponse<String> response = send("POST", "/users",
                "{\"name\":\"Mamadu\",\"email\":\"mamadu@example.com\"}", "application/json", null);

        assertEquals(200, response.statusCode());
        assertEquals("{\"id\":1,\"name\":\"Mamadu\",\"email\":\"mamadu@example.com\"}", response.body());
    }

    @Test
    void invalidInputAndNegotiationFailuresUseTheirStatuses() throws Exception {
        assertEquals(400, send("GET", "/users/abc", null, null, null).statusCode());
        assertEquals(400, send("POST", "/users", "{\"name\":", "application/json", null).statusCode());
        assertEquals(406, send("GET", "/users/42", null, null, "text/html").statusCode());
        assertEquals(415, send("POST", "/users", "<user/>", "application/xml", null).statusCode());
        assertEquals("Hello World", send("GET", "/hello", null, null, null).body());
    }

    private HttpResponse<String> send(String method, String path, String body, String contentType, String accept)
            throws IOException, InterruptedException {
        HttpRequest.Builder request = HttpRequest.newBuilder(URI.create("http://127.0.0.1:" + runtime.port() + path))
                .method(method, body == null ? BodyPublishers.noBody() : BodyPublishers.ofString(body));
        if (contentType != null) {
            request.header("Content-Type", contentType);
        }
        if (accept != null) {
            request.header("Accept", accept);
        }
        return client.send(request.build(), BodyHandlers.ofString());
    }
}
